### ISSUE TITLE
There are some troubles using CRoaring in MacOS.

### ISSUE THREAD

**Issue by Flians** [lemire/CRoaringUnityBuild#1]
I used the CRoaring in my program. but it shows some bugs.

```
#include "roaring.hh"

Undefined symbols for architecture x86_64:
  "_ra_clear", referenced from:
      Roaring::~Roaring() in graph.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by lemire** [comment]
You need to be building and linking the c file. The header file does not contain the function definitions, which is what the error is telling you:

```
echo -e "#include <roaring.hh>\n int main(){Roaring x;}" > test.cpp && cc -c roaring.c -I. -std=c11 && c++ -o test test.cpp roaring.o -I. -std=c++11
```

> but it shows some bugs.

Unlikely. It is more likely that you are not compiling the function definitions as part of your project.

**Comment by Flians** [comment]
> You need to be building and linking the c file. The header file does not contain the function definitions, which is what the error is telling you:
> 
> ```
> echo -e "#include <roaring.hh>\n int main(){Roaring x;}" > test.cpp && cc -c roaring.c -I. -std=c11 && c++ -o test test.cpp roaring.o -I. -std=c++11
> ```
> 
> > but it shows some bugs.
> 
> Unlikely. It is more likely that you are not compiling the function definitions as part of your project.

My problem has been solved. Thank you!
